version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
      - bundle:/usr/local/bundle
      - /app/tmp
      - /app/tmp/pids
      - /app/log
      - /app/.git
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  bundle:
    driver: local
  bundle_install:
    driver: local
